name = "Breaking New Ground"
author = "Sir Bobbing"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35268d0d2ecdec6d50bafdfd8f3cfd84864e860d8d2c5a3e33c92597655d9bee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
acceptable-game-versions = ["1.21.1"]
