name = "Breaking New Ground"
author = "Sir Bobbing"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1e6502618914a17e2f0f0fed0138db62ea6d5aa7d86297fe703451431f85e64"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
acceptable-game-versions = ["1.21.1"]
