name = "Breaking New Ground"
author = "Sir Bobbing"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66ed8622d1a77024b8c8f731d8b8d3de3bb90735b1575de6586f3e2cefa5f158"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
acceptable-game-versions = ["1.21.1"]
