version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = false
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
everycomp = true
streamsreflowing = true
farmersdelight = true
spelunkery = true
nomansland = true
createpropulsion = true
simulatedcoasters = true
brewinandchewin = true
etched = true
another_furniture = true
easyanvils = true
copycats = true
dndecor = true
redomesticate = true
dramaticdoors = true
chalk = true
sootychimneys = true
envelope = true
sleep_tight = true
amendments = true
compactflap = true
handcrafted = true
moonlight = true
chunkloaders = true
treechop = true
exposure = true
offroad = true
kubejs = true
glow = true
supplementaries = true
drivebysable = true
incubation = true
clutternomore = true
tfmg = true
vista = true
create = true
aeronautics = true
mannequins = true
simulated = true
vsfluidlink = true
scguns = true
architects_palette = true
minecraft = true
lootr = true
create_connected = true
powergrid = true
malum = true
endermanoverhaul = true
sliceanddice = true
creeperoverhaul = true
decorative_blocks = true
tradingpost = true
immersiveenchanting = true
reliable_backpacks = true
armourers_workshop = true
toms_storage = true
aeroworks = true
