gamerule.mobExplosionDropDecay=false
gamerule.blockExplosionDropDecay=false
gamerule.commandBlockOutput=false
gamerule.playersSleepingPercentage=50
gamerule.doImmediateRespawn=true
gamerule.doInsomnia=false
